exports.bands = [
    {name: "2190m", start: 0.136, end: 0.137},
    {name: "560m", start: 0.501, end: 0.504},
    {name: "160m", start: 1.8, end: 2.0},
    {name: "80m", start: 3.5, end: 4.0},
    {name: "60m", start: 5.102, end: 5.404},
    {name: "40m", start: 7.0, end: 7.3},
    {name: "30m", start: 10.0, end: 10.15},
    {name: "20m", start: 14.0, end: 14.35},
    {name: "17m", start: 18.068, end: 18.168},
    {name: "15m", start: 21.0, end: 21.45},
    {name: "12m", start: 24.890, end: 24.99},
    {name: "10m", start: 28.0, end: 29.7},
    {name: "6m", start: 50, end: 54},
    {name: "4m", start: 70, end: 71},
    {name: "2m", start: 144, end: 148},
    {name: "1.25m", start: 222, end: 225},
    {name: "70cm", start: 420, end: 450},
    {name: "33cm", start: 902, end: 928},
    {name: "23cm", start: 1240, end: 1300},
    {name: "13cm", start: 2300, end: 2450},
    {name: "9cm", start: 3300, end: 3500},
    {name: "6cm", start: 5650, end: 5925},
    {name: "3cm", start: 10000, end: 10500},
    {name: "1.25cm", start: 24000, end: 24250},
    {name: "6mm", start: 47000, end: 47200},
    {name: "4mm", start: 75500, end: 81000},
    {name: "2.5mm", start: 119980, end: 120020},
    {name: "2mm", start: 142000, end: 149000},
    {name: "1mm", start: 241000, end: 250000}
];

exports.modes = [
    {name: "CW"},
    {name: "SSB", submodes: [
        {name: "LSB"},
        {name: "USB"}
    ]},
    {name: "AM"},
    {name: "FM"},
    {name: "PSK", submodes: [
        {name: "PSK31"},
        {name: "PSK63"},
        {name: "PSK63F"},
        {name: "PSK125"},
        {name: "PSK250"},
        {name: "PSK500"},
        {name: "PSK1000"},
        {name: "QPSK31"},
        {name: "QPSK63"},
        {name: "QPSK125"},
        {name: "QPSK250"},
        {name: "QPSK500"}
    ]},
    {name: "RTTY"},
    {name: "MFSK", submodes: [
        {name: "MFSK4"},
        {name: "MFSK8"},
        {name: "MFSK11"},
        {name: "MFSK16"},
        {name: "MFSK22"},
        {name: "MFSK31"},
        {name: "MFSK32"}
    ]},
    {name: "OLIVIA", submodes: [
        {name: "OLIVIA 4/125"},
        {name: "OLIVIA 4/250"},
        {name: "OLIVIA 8/250"},
        {name: "OLIVIA 8/500"},
        {name: "OLIVIA 16/500"},
        {name: "OLIVIA 16/1000"},
        {name: "OLIVIA 32/1000"},
    ]},
    {name: "JT65", submodes: [
        {name: "JT65A"},
        {name: "JT65B"},
        {name: "JT65B2"},
        {name: "JT65C"},
        {name: "JT65C2"}
    ]},
    {name: "JT9", submodes: [
        {name: "JT9-1"},
        {name: "JT9-1"},
        {name: "JT9-2"},
        {name: "JT9-5"},
        {name: "JT9-10"},
        {name: "JT9-30"}
    ]},
    {name: "HELL", submodes: [
        {name: "FMHELL"},
        {name: "FSKHELL"},
        {name: "HELL80"},
        {name: "HFSK"},
        {name: "PSKHELL"}
    ]},
    {name: "CONTESTIA"},
    {name: "DOMINO", submodes: [
        {name: "DOMINOEX"},
        {name: "DOMINOF"},
    ]},
    {name: "MT63"},
    {name: "FSK441"},
    {name: "DIGITALVOICE"},
    {name: "DSTAR"},
    {name: "PKT"},
    {name: "ATV"},
    {name: "SSTV"}
]

exports.propagation = [
    {name: "AUR", desc: "Aurora"},
    {name: "AUE", desc: "Aurora-E"},
    {name: "BS", desc: "Back scatter"},
    {name: "ECH", desc: "EchoLink"},
    {name: "EME", desc: "Earth-Moon-Earth"},
    {name: "ES", desc: "Sporadic E"},
    {name: "FAI", desc: "Field Aligned Irregularities"},
    {name: "F2", desc: "F2 Reflection"},
    {name: "INTERNET", desc: "Internet-assisted"},
    {name: "ION", desc: "Ionoscatter"},
    {name: "IRL", desc: "IRLP"},
    {name: "MS", desc: "Meteor scatter"},
    {name: "RPT", desc: "Terrestrial or atmospheric repeater or transponder"},
    {name: "RS", desc: "Rain scatter"},
    {name: "SAT", desc: "Satellite"},
    {name: "TEP", desc: "Trans-equatorial"},
    {name: "TR", desc: "Tropospheric ducting"}
];

exports.dxcc_entities = [
    {id: 1, name: "CANADA"},
    {id: 2, name: "ABU AIL IS", deleted: true},
    {id: 3, name: "AFGHANISTAN"},
    {id: 4, name: "AGALEGA & ST BRANDON"},
    {id: 5, name: "ALAND IS"},
    {id: 6, name: "ALASKA"},
    {id: 7, name: "ALBANIA"},
    {id: 8, name: "ALDABRA", deleted: true},
    {id: 9, name: "AMERICAN SAMOA"},
    {id: 10, name: "AMSTERDAM & ST PAUL"},
    {id: 11, name: "ANDAMAN & NICOBAR IS"},
    {id: 12, name: "ANGUILLA"},
    {id: 13, name: "ANTARCTICA"},
    {id: 14, name: "ARMENIA"},
    {id: 15, name: "ASIATIC RUSSIA"},
    {id: 16, name: "AUCKLAND & CAMPBELL"},
    {id: 17, name: "AVES ISLAND"},
    {id: 18, name: "AZERBAIJAN"},
    {id: 19, name: "BAJO NUEVO", deleted: true},
    {id: 20, name: "BAKER, HOWLAND IS"},
    {id: 21, name: "BALEARIC IS"},
    {id: 22, name: "PALAU"},
    {id: 23, name: "BLENHEIM REEF", deleted: true},
    {id: 24, name: "BOUVET"},
    {id: 25, name: "BRITISH N. BORNEO", deleted: true},
    {id: 26, name: "BRITISH SOMALI", deleted: true},
    {id: 27, name: "BELARUS"},
    {id: 28, name: "CANAL ZONE", deleted: true},
    {id: 29, name: "CANARY IS"},
    {id: 30, name: "CELEBE/MOLUCCA IS", deleted: true},
    {id: 31, name: "C KIRIBATI"},
    {id: 32, name: "CEUTA & MELILLA"},
    {id: 33, name: "CHAGOS"},
    {id: 34, name: "CHATHAM IS"},
    {id: 35, name: "CHRISTMAS IS"},
    {id: 36, name: "CLIPPERTON IS"},
    {id: 37, name: "COCOS ISLAND"},
    {id: 38, name: "COCOS-KEELING IS"},
    {id: 39, name: "COMOROS  ", deleted: true},
    {id: 40, name: "CRETE"},
    {id: 41, name: "CROZET"},
    {id: 42, name: "DAMAO, DUI", deleted: true},
    {id: 43, name: "DESECHEO IS"},
    {id: 44, name: "DESROCHES", deleted: true},
    {id: 45, name: "DODECANESE"},
    {id: 46, name: "EAST MALAYSIA"},
    {id: 47, name: "EASTER IS"},
    {id: 48, name: "EASTERN KIRIBATI"},
    {id: 49, name: "EQUATORIAL GUINEA"},
    {id: 50, name: "MEXICO"},
    {id: 51, name: "ERITREA"},
    {id: 52, name: "ESTONIA"},
    {id: 53, name: "ETHIOPIA"},
    {id: 54, name: "EUROPEAN RUSSIA"},
    {id: 55, name: "FARQUHAR", deleted: true},
    {id: 56, name: "FERNANDO DE NORONHA"},
    {id: 57, name: "FRENCH EQ. AFRICA", deleted: true},
    {id: 58, name: "FRENCH INDO-CHINA", deleted: true},
    {id: 59, name: "FRENCH WEST AFRICA", deleted: true},
    {id: 60, name: "BAHAMAS"},
    {id: 61, name: "FRANZ JOSEF LAND"},
    {id: 62, name: "BARBADOS"},
    {id: 63, name: "FRENCH GUIANA"},
    {id: 64, name: "BERMUDA"},
    {id: 65, name: "BRITISH VIRGIN IS"},
    {id: 66, name: "BELIZE"},
    {id: 67, name: "FRENCH INDIA", deleted: true},
    {id: 68, name: "SAUDI/KUWAIT N.Z.", deleted: true},
    {id: 69, name: "CAYMAN ISLANDS"},
    {id: 70, name: "CUBA"},
    {id: 71, name: "GALAPAGOS"},
    {id: 72, name: "DOMINICAN REPUBLIC"},
    {id: 74, name: "EL SALVADOR"},
    {id: 75, name: "GEORGIA"},
    {id: 76, name: "GUATEMALA"},
    {id: 77, name: "GRENADA"},
    {id: 78, name: "HAITI"},
    {id: 79, name: "GUADELOUPE"},
    {id: 80, name: "HONDURAS"},
    {id: 81, name: "GERMANY", deleted: true},
    {id: 82, name: "JAMAICA"},
    {id: 84, name: "MARTINIQUE"},
    {id: 85, name: "BONAIRE,CURACAO", deleted: true},
    {id: 86, name: "NICARAGUA"},
    {id: 88, name: "PANAMA"},
    {id: 89, name: "TURKS & CAICOS IS"},
    {id: 90, name: "TRINIDAD & TOBAGO"},
    {id: 91, name: "ARUBA"},
    {id: 93, name: "GEYSER REEF", deleted: true},
    {id: 94, name: "ANTIGUA & BARBUDA"},
    {id: 95, name: "DOMINICA"},
    {id: 96, name: "MONTSERRAT"},
    {id: 97, name: "ST LUCIA"},
    {id: 98, name: "ST VINCENT"},
    {id: 99, name: "GLORIOSO IS"},
    {id: 100, name: "ARGENTINA"},
    {id: 101, name: "GOA", deleted: true},
    {id: 102, name: "GOLD COAST, TOGOLAND", deleted: true},
    {id: 103, name: "GUAM"},
    {id: 104, name: "BOLIVIA"},
    {id: 105, name: "GUANTANAMO BAY"},
    {id: 106, name: "GUERNSEY"},
    {id: 107, name: "GUINEA"},
    {id: 108, name: "BRAZIL"},
    {id: 109, name: "GUINEA-BISSAU"},
    {id: 110, name: "HAWAII"},
    {id: 111, name: "HEARD IS"},
    {id: 112, name: "CHILE"},
    {id: 113, name: "IFNI", deleted: true},
    {id: 114, name: "ISLE OF MAN"},
    {id: 115, name: "ITALIAN SOMALI", deleted: true},
    {id: 116, name: "COLOMBIA"},
    {id: 117, name: "ITU HQ"},
    {id: 118, name: "JAN MAYEN"},
    {id: 119, name: "JAVA", deleted: true},
    {id: 120, name: "ECUADOR"},
    {id: 122, name: "JERSEY"},
    {id: 123, name: "JOHNSTON IS"},
    {id: 124, name: "JUAN DE NOVA"},
    {id: 125, name: "JUAN FERNANDEZ"},
    {id: 126, name: "KALININGRAD"},
    {id: 127, name: "KAMARAN IS", deleted: true},
    {id: 128, name: "KARELO-FINN REP", deleted: true},
    {id: 129, name: "GUYANA"},
    {id: 130, name: "KAZAKHSTAN"},
    {id: 131, name: "KERGUELEN"},
    {id: 132, name: "PARAGUAY"},
    {id: 133, name: "KERMADEC"},
    {id: 134, name: "KINGMAN REEF"},
    {id: 135, name: "KYRGYZSTAN"},
    {id: 136, name: "PERU"},
    {id: 137, name: "REPUBLIC OF KOREA"},
    {id: 138, name: "KURE ISLAND"},
    {id: 139, name: "KURIA MURIA IS", deleted: true},
    {id: 140, name: "SURINAME"},
    {id: 141, name: "FALKLAND IS"},
    {id: 142, name: "LAKSHADWEEP ISLANDS"},
    {id: 143, name: "LAOS"},
    {id: 144, name: "URUGUAY"},
    {id: 145, name: "LATVIA"},
    {id: 146, name: "LITHUANIA"},
    {id: 147, name: "LORD HOWE IS"},
    {id: 148, name: "VENEZUELA"},
    {id: 149, name: "AZORES"},
    {id: 150, name: "AUSTRALIA"},
    {id: 151, name: "MALYJ VYSOTSKI IS ", deleted: true},
    {id: 152, name: "MACAO"},
    {id: 153, name: "MACQUARIE IS"},
    {id: 154, name: "YEMEN ARAB REP", deleted: true},
    {id: 155, name: "MALAYA", deleted: true},
    {id: 157, name: "NAURU"},
    {id: 158, name: "VANUATU"},
    {id: 159, name: "MALDIVES"},
    {id: 160, name: "TONGA"},
    {id: 161, name: "MALPELO IS"},
    {id: 162, name: "NEW CALEDONIA"},
    {id: 163, name: "PAPUA NEW GUINEA"},
    {id: 164, name: "MANCHURIA", deleted: true},
    {id: 165, name: "MAURITIUS IS"},
    {id: 166, name: "MARIANA IS"},
    {id: 167, name: "MARKET REEF"},
    {id: 168, name: "MARSHALL IS"},
    {id: 169, name: "MAYOTTE"},
    {id: 170, name: "NEW ZEALAND"},
    {id: 171, name: "MELLISH REEF"},
    {id: 172, name: "PITCAIRN IS"},
    {id: 173, name: "MICRONESIA"},
    {id: 174, name: "MIDWAY IS"},
    {id: 175, name: "FRENCH POLYNESIA"},
    {id: 176, name: "FIJI"},
    {id: 177, name: "MINAMI TORISHIMA"},
    {id: 178, name: "MINERVA REEF", deleted: true},
    {id: 179, name: "MOLDOVA"},
    {id: 180, name: "MOUNT ATHOS"},
    {id: 181, name: "MOZAMBIQUE"},
    {id: 182, name: "NAVASSA IS"},
    {id: 183, name: "NETHERLANDS BORNEO", deleted: true},
    {id: 184, name: "NETHERLANDS N GUINEA ", deleted: true},
    {id: 185, name: "SOLOMON ISLANDS"},
    {id: 186, name: "NEWFOUNDLAND, LABRADOR", deleted: true},
    {id: 187, name: "NIGER"},
    {id: 188, name: "NIUE"},
    {id: 189, name: "NORFOLK IS"},
    {id: 190, name: "SAMOA"},
    {id: 191, name: "N COOK IS"},
    {id: 192, name: "OGASAWARA"},
    {id: 193, name: "OKINAWA", deleted: true},
    {id: 194, name: "OKINO TORI-SHIMA", deleted: true},
    {id: 195, name: "ANNOBON I."},
    {id: 196, name: "PALESTINE", deleted: true},
    {id: 197, name: "PALMYRA & JARVIS IS"},
    {id: 198, name: "PAPUA TERR", deleted: true},
    {id: 199, name: "PETER I IS"},
    {id: 200, name: "PORTUGUESE TIMOR", deleted: true},
    {id: 201, name: "PRINCE EDWARD & MARION"},
    {id: 202, name: "PUERTO RICO"},
    {id: 203, name: "ANDORRA"},
    {id: 204, name: "REVILLAGIGEDO"},
    {id: 205, name: "ASCENSION ISLAND"},
    {id: 206, name: "AUSTRIA"},
    {id: 207, name: "RODRIGUEZ IS"},
    {id: 208, name: "RUANDA-URUNDI", deleted: true},
    {id: 209, name: "BELGIUM"},
    {id: 210, name: "SAAR", deleted: true},
    {id: 211, name: "SABLE ISLAND"},
    {id: 212, name: "BULGARIA"},
    {id: 213, name: "SAINT MARTIN"},
    {id: 214, name: "CORSICA"},
    {id: 215, name: "CYPRUS"},
    {id: 216, name: "SAN ANDRES & PROVIDENCIA"},
    {id: 217, name: "SAN FELIX"},
    {id: 218, name: "CZECHOSLOVAKIA", deleted: true},
    {id: 219, name: "SAO TOME & PRINCIPE"},
    {id: 220, name: "SARAWAK", deleted: true},
    {id: 221, name: "DENMARK"},
    {id: 222, name: "FAROE IS"},
    {id: 223, name: "ENGLAND"},
    {id: 224, name: "FINLAND"},
    {id: 225, name: "SARDINIA"},
    {id: 226, name: "SAUDI/IRAQ N.Z.", deleted: true},
    {id: 227, name: "FRANCE"},
    {id: 228, name: "SERRANA BANK & RONCADOR CAY", deleted: true},
    {id: 229, name: "GERMAN DEM. REP.", deleted: true},
    {id: 230, name: "FED REP OF GERMANY"},
    {id: 231, name: "SIKKIM", deleted: true},
    {id: 232, name: "SOMALIA"},
    {id: 233, name: "GIBRALTAR"},
    {id: 234, name: "S COOK IS"},
    {id: 235, name: "SOUTH GEORGIA IS"},
    {id: 236, name: "GREECE"},
    {id: 237, name: "GREENLAND"},
    {id: 238, name: "SOUTH ORKNEY IS"},
    {id: 239, name: "HUNGARY"},
    {id: 240, name: "SOUTH SANDWICH ISLANDS"},
    {id: 241, name: "SOUTH SHETLAND ISLANDS"},
    {id: 242, name: "ICELAND"},
    {id: 243, name: "DEM REP OF YEMEN", deleted: true},
    {id: 244, name: "SOUTHERN SUDAN", deleted: true},
    {id: 245, name: "IRELAND"},
    {id: 246, name: "SOV MILITARY ORDER OF MALTA"},
    {id: 247, name: "SPRATLY IS"},
    {id: 248, name: "ITALY"},
    {id: 249, name: "ST KITTS & NEVIS"},
    {id: 250, name: "ST HELENA IS"},
    {id: 251, name: "LIECHTENSTEIN"},
    {id: 252, name: "ST PAUL ISLAND"},
    {id: 253, name: "ST. PETER & ST. PAUL ROCKS"},
    {id: 254, name: "LUXEMBOURG"},
    {id: 255, name: "SINT MAARTEN, SABA, ST EUSTATIUS"},
    {id: 256, name: "MADEIRA IS"},
    {id: 257, name: "MALTA"},
    {id: 258, name: "SUMATRA", deleted: true},
    {id: 259, name: "SVALBARD IS"},
    {id: 260, name: "MONACO"},
    {id: 261, name: "SWAN ISLAND", deleted: true},
    {id: 262, name: "TAJIKISTAN"},
    {id: 263, name: "NETHERLANDS"},
    {id: 264, name: "TANGIER", deleted: true},
    {id: 265, name: "NORTHERN IRELAND"},
    {id: 266, name: "NORWAY"},
    {id: 267, name: "TERR NEW GUINEA", deleted: true},
    {id: 268, name: "TIBET", deleted: true},
    {id: 269, name: "POLAND"},
    {id: 270, name: "TOKELAU IS"},
    {id: 271, name: "TRIESTE", deleted: true},
    {id: 272, name: "PORTUGAL"},
    {id: 273, name: "TRINDADE & MARTIN VAZ ISLANDS"},
    {id: 274, name: "TRISTAN DA CUNHA & GOUGH IS"},
    {id: 275, name: "ROMANIA"},
    {id: 276, name: "TROMELIN"},
    {id: 277, name: "ST PIERRE & MIQUELON"},
    {id: 278, name: "SAN MARINO"},
    {id: 279, name: "SCOTLAND"},
    {id: 280, name: "TURKMENISTAN"},
    {id: 281, name: "SPAIN"},
    {id: 282, name: "TUVALU"},
    {id: 283, name: "UK BASES ON CYPRUS"},
    {id: 284, name: "SWEDEN"},
    {id: 285, name: "US VIRGIN ISLANDS"},
    {id: 286, name: "UGANDA"},
    {id: 287, name: "SWITZERLAND"},
    {id: 288, name: "UKRAINE"},
    {id: 289, name: "UNITED NATIONS HQ"},
    {id: 291, name: "UNITED STATES"},
    {id: 292, name: "UZBEKISTAN"},
    {id: 293, name: "VIETNAM"},
    {id: 294, name: "WALES"},
    {id: 295, name: "VATICAN"},
    {id: 296, name: "SERBIA"},
    {id: 297, name: "WAKE IS"},
    {id: 298, name: "WALLIS & FUTUNA"},
    {id: 299, name: "WEST MALAYSIA"},
    {id: 301, name: "W KIRIBATI"},
    {id: 302, name: "WESTERN SAHARA"},
    {id: 303, name: "WILLIS IS"},
    {id: 304, name: "BAHRAIN"},
    {id: 305, name: "BANGLADESH"},
    {id: 306, name: "BHUTAN"},
    {id: 307, name: "ZANZIBAR", deleted: true},
    {id: 308, name: "COSTA RICA"},
    {id: 309, name: "MYANMAR"},
    {id: 312, name: "CAMBODIA"},
    {id: 315, name: "SRI LANKA"},
    {id: 318, name: "CHINA"},
    {id: 321, name: "HONG KONG"},
    {id: 324, name: "INDIA"},
    {id: 327, name: "INDONESIA"},
    {id: 330, name: "IRAN"},
    {id: 333, name: "IRAQ"},
    {id: 336, name: "ISRAEL"},
    {id: 339, name: "JAPAN"},
    {id: 342, name: "JORDAN"},
    {id: 344, name: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA"},
    {id: 345, name: "BRUNEI"},
    {id: 348, name: "KUWAIT"},
    {id: 354, name: "LEBANON"},
    {id: 363, name: "MONGOLIA"},
    {id: 369, name: "NEPAL"},
    {id: 370, name: "OMAN"},
    {id: 372, name: "PAKISTAN"},
    {id: 375, name: "PHILIPPINES"},
    {id: 376, name: "QATAR"},
    {id: 378, name: "SAUDI ARABIA"},
    {id: 379, name: "SEYCHELLES"},
    {id: 381, name: "SINGAPORE"},
    {id: 382, name: "DJIBOUTI"},
    {id: 384, name: "SYRIA"},
    {id: 386, name: "TAIWAN"},
    {id: 387, name: "THAILAND"},
    {id: 390, name: "TURKEY"},
    {id: 391, name: "UNITED ARAB EMIRATES"},
    {id: 400, name: "ALGERIA"},
    {id: 401, name: "ANGOLA"},
    {id: 402, name: "BOTSWANA"},
    {id: 404, name: "BURUNDI"},
    {id: 406, name: "CAMEROON"},
    {id: 408, name: "CENTRAL AFRICAN REPUBLIC"},
    {id: 409, name: "CAPE VERDE"},
    {id: 410, name: "CHAD"},
    {id: 411, name: "COMOROS"},
    {id: 412, name: "REPUBLIC OF THE CONGO"},
    {id: 414, name: "DEM. REPUBLIC OF THE CONGO"},
    {id: 416, name: "BENIN"},
    {id: 420, name: "GABON"},
    {id: 422, name: "THE GAMBIA"},
    {id: 424, name: "GHANA"},
    {id: 428, name: "COTE D'IVOIRE"},
    {id: 430, name: "KENYA"},
    {id: 432, name: "LESOTHO"},
    {id: 434, name: "LIBERIA"},
    {id: 436, name: "LIBYA"},
    {id: 438, name: "MADAGASCAR"},
    {id: 440, name: "MALAWI"},
    {id: 442, name: "MALI"},
    {id: 444, name: "MAURITANIA"},
    {id: 446, name: "MOROCCO"},
    {id: 450, name: "NIGERIA"},
    {id: 452, name: "ZIMBABWE"},
    {id: 453, name: "REUNION"},
    {id: 454, name: "RWANDA"},
    {id: 456, name: "SENEGAL"},
    {id: 458, name: "SIERRA LEONE"},
    {id: 460, name: "ROTUMA IS"},
    {id: 462, name: "REPUBLIC OF SOUTH AFRICA"},
    {id: 464, name: "NAMIBIA"},
    {id: 466, name: "SUDAN"},
    {id: 468, name: "SWAZILAND"},
    {id: 470, name: "TANZANIA"},
    {id: 474, name: "TUNISIA"},
    {id: 478, name: "EGYPT"},
    {id: 480, name: "BURKINA-FASO"},
    {id: 482, name: "ZAMBIA"},
    {id: 483, name: "TOGO"},
    {id: 488, name: "WALVIS BAY", deleted: true},
    {id: 489, name: "CONWAY REEF"},
    {id: 490, name: "BANABA ISLAND"},
    {id: 492, name: "YEMEN"},
    {id: 493, name: "PENGUIN ISLANDS", deleted: true},
    {id: 497, name: "CROATIA"},
    {id: 499, name: "SLOVENIA"},
    {id: 501, name: "BOSNIA-HERZEGOVINA"},
    {id: 502, name: "MACEDONIA"},
    {id: 503, name: "CZECH REPUBLIC"},
    {id: 504, name: "SLOVAK REPUBLIC"},
    {id: 505, name: "PRATAS IS"},
    {id: 506, name: "SCARBOROUGH REEF"},
    {id: 507, name: "TEMOTU PROVINCE"},
    {id: 508, name: "AUSTRAL IS"},
    {id: 509, name: "MARQUESAS IS"},
    {id: 510, name: "PALESTINE"},
    {id: 511, name: "TIMOR-LESTE"},
    {id: 512, name: "CHESTERFIELD IS"},
    {id: 513, name: "DUCIE IS"},
    {id: 514, name: "MONTENEGRO"},
    {id: 515, name: "SWAINS ISLAND"},
    {id: 516, name: "ST. BARTHELEMY"},
    {id: 517, name: "CURACAO"},
    {id: 518, name: "SINT MAARTEN"},
    {id: 519, name: "ST EUSTATIUS AND SABA"},
    {id: 520, name: "BONAIRE"},
    {id: 521, name: "SOUTH SUDAN"}
];

exports.contests = [
    {id: "070-PSKFEST", desc: "PODXS PSKFest"},
    {id: "070-VALENTINE-SPRINT", desc: "PODXS Valentine Sprint"},
    {id: "070-ST-PATS-DAY", desc: "PODXS St. Patricks Day"},
    {id: "070-31-FLAVORS", desc: "PODXS 31 Flavors"},
    {id: "070-3-DAY", desc: "PODXS Three Day Weekend"},
    {id: "070-40M-SPRINT", desc: "PODXS 40m Firecracker Sprint"},
    {id: "070-80M-SPRINT", desc: "PODXS 80m Jay Hudak Memorial Sprint"},
    {id: "070-160M-SPRINT", desc: "PODXS Great Pumpkin Sprint"},
    {id: "7QP", desc: "7th-Area QSO Party"},
    {id: "AL-QSO-PARTY", desc: "Alabama QSO Party"},
    {id: "ALL-ASIAN-DX-CW", desc: "JARL All Asian DX Contest (CW)"},
    {id: "ALL-ASIAN-DX-PHONE", desc: "JARL All Asian DX Contest (PHONE)"},
    {id: "ANARTS-RTTY", desc: "ANARTS WW RTTY"},
    {id: "ANATOLIAN-RTTY", desc: "Anatolian WW RTTY"},
    {id: "AP-SPRINT", desc: "Asia - Pacific Sprint"},
    {id: "AR-QSO-PARTY", desc: "Arkansas QSO Party"},
    {id: "ARI-DX", desc: "ARI DX Contest"},
    {id: "ARRL-10", desc: "ARRL 10 Meter Contest"},
    {id: "ARRL-160", desc: "ARRL 160 Meter Contest"},
    {id: "ARRL-DX-CW", desc: "ARRL International DX Contest (CW)"},
    {id: "ARRL-DX-SSB", desc: "ARRL International DX Contest (Phone)"},
    {id: "ARRL-FIELD-DAY", desc: "ARRL Field Day"},
    {id: "ARRL-RTTY", desc: "ARRL RTTY Round-Up"},
    {id: "ARRL-SS-CW", desc: "ARRL November Sweepstakes (CW)"},
    {id: "ARRL-SS-SSB", desc: "ARRL November Sweepstakes (Phone)"},
    {id: "ARRL-UHF-AUG", desc: "ARRL August UHF Contest"},
    {id: "ARRL-VHF-JAN", desc: "ARRL January VHF Sweepstakes"},
    {id: "ARRL-VHF-JUN", desc: "ARRL June VHF QSO Party"},
    {id: "ARRL-VHF-SEP", desc: "ARRL September VHF QSO Party"},
    {id: "AZ-QSO-PARTY", desc: "Arizona QSO Party"},
    {id: "BARTG-RTTY", desc: "BARTG Spring RTTY Contest"},
    {id: "BARTG-SPRINT", desc: "BARTG Sprint Contest"},
    {id: "BC-QSO-PARTY", desc: "British Columbia QSO Party"},
    {id: "CA-QSO-PARTY", desc: "California QSO Party"},
    {id: "CO-QSO-PARTY", desc: "Colorado QSO Party"},
    {id: "CQ-160-CW", desc: "CQ WW 160 Meter DX Contest (CW)"},
    {id: "CQ-160-SSB", desc: "CQ WW 160 Meter DX Contest (SSB)"},
    {id: "CQ-M", desc: "CQ-M International DX Contest"},
    {id: "CQ-VHF", desc: "CQ World-Wide VHF Contest"},
    {id: "CQ-WPX-CW", desc: "CQ WW WPX Contest (CW)"},
    {id: "CQ-WPX-RTTY", desc: "CQ/RJ WW RTTY WPX Contest"},
    {id: "CQ-WPX-SSB", desc: "CQ WW WPX Contest (SSB)"},
    {id: "CQ-WW-CW", desc: "CQ WW DX Contest (CW)"},
    {id: "CQ-WW-RTTY", desc: "CQ/RJ WW RTTY DX Contest"},
    {id: "CQ-WW-SSB", desc: "CQ WW DX Contest (SSB)"},
    {id: "CWOPS-CWT", desc: "CWops Mini-CWT Test"},
    {id: "CIS-DX", desc: "CIS DX Contest"},
    {id: "CT-QSO-PARTY", desc: "Connecticut QSO Party"},
    {id: "DARC-WAEDC-CW", desc: "WAE DX Contest (CW)"},
    {id: "DARC-WAEDC-RTTY", desc: "WAE DX Contest (RTTY)"},
    {id: "DARC-WAEDC-SSB", desc: "WAE DX Contest (SSB)"},
    {id: "DARC-WAG", desc: "DARC Worked All Germany"},
    {id: "DE-QSO-PARTY", desc: "Delaware QSO Party"},
    {id: "DL-DX-RTTY", desc: "DL-DX RTTY Contest"},
    {id: "EA-RTTY (Deprecated) ", desc: "Unión de Radioaficionados Españoles RTTY Contest"},
    {id: "EA-WW-RTTY", desc: "Unión de Radioaficionados Españoles RTTY Contest"},
    {id: "EPC-PSK63", desc: "PSK63 QSO Party"},
    {id: "EU Sprint", desc: "EU Sprint"},
    {id: "EUCW160M", desc: "European CW Association 160m CW Party"},
    {id: "EU-HF", desc: "EU HF Championship"},
    {id: "EU-PSK-DX", desc: "EU PSK DX Contest"},
    {id: "Fall Sprint", desc: "FISTS Fall Sprint"},
    {id: "FL-QSO-PARTY", desc: "Florida QSO Party"},
    {id: "GA-QSO-PARTY", desc: "Georgia QSO Party"},
    {id: "HELVETIA", desc: "Helvetia Contest"},
    {id: "HI-QSO-PARTY", desc: "Hawaiian QSO Party"},
    {id: "HOLYLAND", desc: "IARC Holyland Contest"},
    {id: "IARU-FIELD-DAY", desc: "DARC IARU Region 1 Field Day"},
    {id: "IARU-HF", desc: "IARU HF World Championship"},
    {id: "IA-QSO-PARTY", desc: "Iowa QSO Party"},
    {id: "ID-QSO-PARTY", desc: "Idaho QSO Party"},
    {id: "IL QSO Party", desc: "Illinois QSO Party"},
    {id: "IN-QSO-PARTY", desc: "Indiana QSO Party"},
    {id: "JARTS-WW-RTTY", desc: "JARTS WW RTTY"},
    {id: "JIDX-CW", desc: "Japan International DX Contest (CW)"},
    {id: "JIDX-SSB", desc: "Japan International DX Contest (SSB)"},
    {id: "KS-QSO-PARTY", desc: "Kansas QSO Party"},
    {id: "KY-QSO-PARTY", desc: "Kentucky QSO Party"},
    {id: "LA-QSO-PARTY", desc: "Louisiana QSO Party"},
    {id: "LZ DX", desc: "LZ DX Contest"},
    {id: "MAR-QSO-PARTY", desc: "Maritimes QSO Party"},
    {id: "MI-QSO-PARTY", desc: "Michigan QSO Party"},
    {id: "MIDATLANTIC-QSO-PARTY", desc: "Mid-Atlantic QSO Party"},
    {id: "MD-QSO-PARTY", desc: "Maryland QSO Party"},
    {id: "ME-QSO-PARTY", desc: "Maine QSO Party"},
    {id: "MI-QSO-PARTY", desc: "Michigan QSO Party"},
    {id: "MN-QSO-PARTY", desc: "Minnesota QSO Party"},
    {id: "MO-QSO-PARTY", desc: "Missouri QSO Party"},
    {id: "MS-QSO-PARTY", desc: "Mississippi QSO Party"},
    {id: "MT-QSO-PARTY", desc: "Montana QSO Party"},
    {id: "NAQP-CW", desc: "North America QSO Party (CW)"},
    {id: "NAQP-RTTY", desc: "North America QSO Party (RTTY)"},
    {id: "NAQP-SSB", desc: "North America QSO Party (Phone)"},
    {id: "NA-SPRINT-CW", desc: "North America Sprint (CW)"},
    {id: "NA-SPRINT-RTTY", desc: "North America Sprint (RTTY)"},
    {id: "NA-SPRINT-SSB", desc: "North America Sprint (Phone)"},
    {id: "NEQP", desc: "New England QSO Party"},
    {id: "NC-QSO-PARTY", desc: "North Carolina QSO Party"},
    {id: "ND-QSO-PARTY", desc: "North Dakota QSO Party"},
    {id: "NE-QSO-PARTY", desc: "Nebraska QSO Party"},
    {id: "NH-QSO-PARTY", desc: "New Hampshire QSO Party"},
    {id: "NJ-QSO-PARTY", desc: "New Jersey QSO Party"},
    {id: "NM-QSO-PARTY", desc: "New Mexico QSO Party"},
    {id: "NRAU-BALTIC-CW", desc: "NRAU-Baltic Contest (CW)"},
    {id: "NRAU-BALTIC-SSB", desc: "NRAU-Baltic Contest (SSB)"},
    {id: "NV-QSO-PARTY", desc: "Nevada QSO Party"},
    {id: "NY-QSO-PARTY", desc: "New York QSO Party"},
    {id: "OCEANIA-DX-CW", desc: "Oceania DX Contest (CW)"},
    {id: "OCEANIA-DX-SSB", desc: "Oceania DX Contest (SSB)"},
    {id: "OH-QSO-PARTY", desc: "Ohio QSO Party"},
    {id: "OK-DX-RTTY", desc: "Czech Radio Club OK DX Contest"},
    {id: "OK-OM-DX", desc: "Czech Radio Club OK-OM DX Contest"},
    {id: "OK-QSO-PARTY", desc: "Oklahoma QSO Party"},
    {id: "OMISS-QSO-PARTY", desc: "Old Man International Sideband Society QSO Party"},
    {id: "ON-QSO-PARTY", desc: "Ontario QSO Party"},
    {id: "OR-QSO-PARTY", desc: "Oregon QSO Party"},
    {id: "PACC", desc: "Dutch PACC Contest"},
    {id: "PA-QSO-PARTY", desc: "Pennsylvania QSO Party"},
    {id: "QC-QSO-PARTY", desc: "Quebec QSO Party"},
    {id: "RAC ", desc: "Canadian Amateur Radio Society Contest"},
    {id: "RAC-CANADA-DAY", desc: "Canadian Amateur Radio Society Canada Day Contest"},
    {id: "RAC-CANADA-WINTER", desc: "Canadian Amateur Radio Society Canada Winter Contest"},
    {id: "RDAC", desc: "Russian District Award Contest"},
    {id: "RDXC", desc: "Russian DX Contest"},
    {id: "REF-160M", desc: "Reseau des Emetteurs Francais 160m Contest"},
    {id: "REF-CW", desc: "Reseau des Emetteurs Francais Contest (CW)"},
    {id: "REF-SSB", desc: "Reseau des Emetteurs Francais Contest (SSB)"},
    {id: "RI-QSO-PARTY", desc: "Rhode Island QSO Party"},
    {id: "RSGB-160", desc: "1.8Mhz Contest"},
    {id: "RSGB-21/28-CW", desc: "21/28 MHz Contest (CW)"},
    {id: "RSGB-21/28-SSB", desc: "21/28 MHz Contest (SSB)"},
    {id: "RSGB-80M-CC", desc: "80m Club Championships"},
    {id: "RSGB-AFS-CW", desc: "Affiliated Societies Team Contest (CW)"},
    {id: "RSGB-AFS-SSB", desc: "Affiliated Societies Team Contest (SSB)"},
    {id: "RSGB-CLUB-CALLS", desc: "Club Calls"},
    {id: "RSGB-COMMONWEALTH", desc: "Commonwealth Contest"},
    {id: "RSGB-IOTA", desc: "IOTA Contest"},
    {id: "RSGB-LOW-POWER", desc: "Low Power Field Day"},
    {id: "RSGB-NFD", desc: "National Field Day"},
    {id: "RSGB-ROPOCO", desc: "RoPoCo"},
    {id: "RSGB-SSB-FD", desc: "SSB Field Day"},
    {id: "RUSSIAN-RTTY", desc: "Russian Radio RTTY Worldwide Contest"},
    {id: "SAC-CW", desc: "Scandinavian Activity Contest (CW)"},
    {id: "SAC-SSB", desc: "Scandinavian Activity Contest (SSB)"},
    {id: "SARTG-RTTY", desc: "SARTG WW RTTY"},
    {id: "SCC-RTTY", desc: "SCC RTTY Championship"},
    {id: "SC-QSO-PARTY", desc: "South Carolina QSO Party"},
    {id: "SD-QSO-PARTY", desc: "South Dakota QSO Party"},
    {id: "SMP-AUG", desc: "SSA Portabeltest"},
    {id: "SMP-MAY", desc: "SSA Portabeltest"},
    {id: "SPDXContest", desc: "SP DX Contest"},
    {id: "SP-DX-RTTY", desc: "PRC SPDX Contest (RTTY)"},
    {id: "Spring Sprint", desc: "FISTS Spring Sprint"},
    {id: "SR-MARATHON", desc: "Scottish-Russian Marathon"},
    {id: "STEW-PERRY", desc: "Stew Perry Topband Distance Challenge"},
    {id: "Summer Sprint", desc: "FISTS Summer Sprint"},
    {id: "TARA-RTTY", desc: "TARA RTTY Mêlée"},
    {id: "TMC-RTTY", desc: "The Makrothen Contest"},
    {id: "TN-QSO-PARTY", desc: "Tennessee QSO Party"},
    {id: "TX-QSO-PARTY", desc: "Texas QSO Party"},
    {id: "UBA-DX-CW", desc: "UBA Contest (CW)"},
    {id: "UBA-DX-SSB", desc: "UBA Contest (SSB)"},
    {id: "UK-DX-BPSK63", desc: "European PSK Club BPSK63 Contest"},
    {id: "UK-DX-RTTY", desc: "UK DX RTTY Contest"},
    {id: "UKRAINIAN DX", desc: "Ukrainian DX"},
    {id: "UKR-CHAMP-RTTY", desc: "Open Ukraine RTTY Championship"},
    {id: "URE-DX", desc: "Ukrainian DX Contest"},
    {id: "US-COUNTIES-QSO", desc: "Mobile Amateur Awards Club"},
    {id: "UT-QSO-PARTY", desc: "Utah QSO Party"},
    {id: "VENEZ-IND-DAY", desc: "RCV Venezuelan Independence Day Contest"},
    {id: "Virginia QSO Party (deprecated) ", desc: "Virginia QSO Party"},
    {id: "VA-QSO-PARTY", desc: "Virginia QSO Party"},
    {id: "VOLTA-RTTY", desc: "Alessandro Volta RTTY DX Contest"},
    {id: "WA-QSO-PARTY", desc: "Washington QSO Party"},
    {id: "WI-QSO-PARTY", desc: "Wisconsin QSO Party"},
    {id: "WV-QSO-PARTY", desc: "West Virginia QSO Party"},
    {id: "WY-QSO-PARTY", desc: "Wyoming QSO Party"},
    {id: "Winter Sprint", desc: "FISTS Winter Sprint"},
    {id: "XE-INTL-RTTY", desc: "Mexico International Contest (RTTY)"},
    {id: "YUDXC", desc: "YU DX Contest"}
]
