exports.bands = [
    {name: "2190m", start: 0.136, end: 0.137},
    {name: "560m", start: 0.501, end: 0.504},
    {name: "160m", start: 1.8, end: 2.0},
    {name: "80m", start: 3.5, end: 4.0},
    {name: "60m", start: 5.102, end: 5.404},
    {name: "40m", start: 7.0, end: 7.3},
    {name: "30m", start: 10.0, end: 10.15},
    {name: "20m", start: 14.0, end: 14.35},
    {name: "17m", start: 18.068, end: 18.168},
    {name: "15m", start: 21.0, end: 21.45},
    {name: "12m", start: 24.890, end: 24.99},
    {name: "10m", start: 28.0, end: 29.7},
    {name: "6m", start: 50, end: 54},
    {name: "4m", start: 70, end: 71},
    {name: "2m", start: 144, end: 148},
    {name: "1.25m", start: 222, end: 225},
    {name: "70cm", start: 420, end: 450},
    {name: "33cm", start: 902, end: 928},
    {name: "23cm", start: 1240, end: 1300},
    {name: "13cm", start: 2300, end: 2450},
    {name: "9cm", start: 3300, end: 3500},
    {name: "6cm", start: 5650, end: 5925},
    {name: "3cm", start: 10000, end: 10500},
    {name: "1.25cm", start: 24000, end: 24250},
    {name: "6mm", start: 47000, end: 47200},
    {name: "4mm", start: 75500, end: 81000},
    {name: "2.5mm", start: 119980, end: 120020},
    {name: "2mm", start: 142000, end: 149000},
    {name: "1mm", start: 241000, end: 250000}
];

exports.modes = [
    {name: "CW"},
    {name: "SSB", submodes: [
        {name: "LSB"},
        {name: "USB"}
    ]},
    {name: "AM"},
    {name: "FM"},
    {name: "PSK", submodes: [
        {name: "PSK31"},
        {name: "PSK63"},
        {name: "PSK63F"},
        {name: "PSK125"},
        {name: "PSK250"},
        {name: "PSK500"},
        {name: "PSK1000"},
        {name: "QPSK31"},
        {name: "QPSK63"},
        {name: "QPSK125"},
        {name: "QPSK250"},
        {name: "QPSK500"}
    ]},
    {name: "RTTY"},
    {name: "MFSK", submodes: [
        {name: "MFSK4"},
        {name: "MFSK8"},
        {name: "MFSK11"},
        {name: "MFSK16"},
        {name: "MFSK22"},
        {name: "MFSK31"},
        {name: "MFSK32"}
    ]},
    {name: "OLIVIA", submodes: [
        {name: "OLIVIA 4/125"},
        {name: "OLIVIA 4/250"},
        {name: "OLIVIA 8/250"},
        {name: "OLIVIA 8/500"},
        {name: "OLIVIA 16/500"},
        {name: "OLIVIA 16/1000"},
        {name: "OLIVIA 32/1000"},
    ]},
    {name: "JT65", submodes: [
        {name: "JT65A"},
        {name: "JT65B"},
        {name: "JT65B2"},
        {name: "JT65C"},
        {name: "JT65C2"}
    ]},
    {name: "JT9", submodes: [
        {name: "JT9-1"},
        {name: "JT9-1"},
        {name: "JT9-2"},
        {name: "JT9-5"},
        {name: "JT9-10"},
        {name: "JT9-30"}
    ]},
    {name: "HELL", submodes: [
        {name: "FMHELL"},
        {name: "FSKHELL"},
        {name: "HELL80"},
        {name: "HFSK"},
        {name: "PSKHELL"}
    ]},
    {name: "CONTESTIA"},
    {name: "DOMINO", submodes: [
        {name: "DOMINOEX"},
        {name: "DOMINOF"},
    ]},
    {name: "MT63"},
    {name: "FSK441"},
    {name: "DIGITALVOICE"},
    {name: "DSTAR"},
    {name: "PKT"},
    {name: "ATV"},
    {name: "SSTV"}
]

exports.propagation = [
    {name: "AUR", desc: "Aurora"},
    {name: "AUE", desc: "Aurora-E"},
    {name: "BS", desc: "Back scatter"},
    {name: "ECH", desc: "EchoLink"},
    {name: "EME", desc: "Earth-Moon-Earth"},
    {name: "ES", desc: "Sporadic E"},
    {name: "FAI", desc: "Field Aligned Irregularities"},
    {name: "F2", desc: "F2 Reflection"},
    {name: "INTERNET", desc: "Internet-assisted"},
    {name: "ION", desc: "Ionoscatter"},
    {name: "IRL", desc: "IRLP"},
    {name: "MS", desc: "Meteor scatter"},
    {name: "RPT", desc: "Terrestrial or atmospheric repeater or transponder"},
    {name: "RS", desc: "Rain scatter"},
    {name: "SAT", desc: "Satellite"},
    {name: "TEP", desc: "Trans-equatorial"},
    {name: "TR", desc: "Tropospheric ducting"}
];

exports.dxcc_entities = [
    null,
    {id: 1, name: "CANADA", flag: "CA"},
    {id: 2, name: "ABU AIL IS", deleted: true},
    {id: 3, name: "AFGHANISTAN", flag: "AF"},
    {id: 4, name: "AGALEGA & ST BRANDON", flag: "MP"},
    {id: 5, name: "ALAND IS", flag: "AX"},
    {id: 6, name: "ALASKA", flag: "US"},
    {id: 7, name: "ALBANIA", flag: "AL"},
    {id: 8, name: "ALDABRA", deleted: true, flag: "SC"},
    {id: 9, name: "AMERICAN SAMOA", flag: "AS"},
    {id: 10, name: "AMSTERDAM & ST PAUL", flag: "FR"},
    {id: 11, name: "ANDAMAN & NICOBAR IS", flag: "IN"},
    {id: 12, name: "ANGUILLA", flag: "AI"},
    {id: 13, name: "ANTARCTICA", flag: "AQ"},
    {id: 14, name: "ARMENIA", flag: "AM"},
    {id: 15, name: "ASIATIC RUSSIA", flag: "RU"},
    {id: 16, name: "AUCKLAND & CAMPBELL", flag: "NZ"},
    {id: 17, name: "AVES ISLAND", flag: "VE"},
    {id: 18, name: "AZERBAIJAN", flag: "AZ"},
    {id: 19, name: "BAJO NUEVO", deleted: true, flag: "CO"},
    {id: 20, name: "BAKER, HOWLAND IS", flag: "US"},
    {id: 21, name: "BALEARIC IS", flag: "ES"},
    {id: 22, name: "PALAU", flag: "PW"},
    {id: 23, name: "BLENHEIM REEF", deleted: true, flag: "MU"},
    {id: 24, name: "BOUVET", flag: "NO"},
    {id: 25, name: "BRITISH N. BORNEO", deleted: true, flag: "GB"},
    {id: 26, name: "BRITISH SOMALI", deleted: true, flag: "GB"},
    {id: 27, name: "BELARUS", flag: "BY"},
    {id: 28, name: "CANAL ZONE", deleted: true},
    {id: 29, name: "CANARY IS", flag: "IC"},
    {id: 30, name: "CELEBE/MOLUCCA IS", deleted: true, flag: "ID"},
    {id: 31, name: "C KIRIBATI", flag: "KI"},
    {id: 32, name: "CEUTA & MELILLA", flag: "ES"},
    {id: 33, name: "CHAGOS", flag: "GB"},
    {id: 34, name: "CHATHAM IS", flag: "NZ"},
    {id: 35, name: "CHRISTMAS IS", flag: "CX"},
    {id: 36, name: "CLIPPERTON IS", flag: "FR"},
    {id: 37, name: "COCOS ISLAND", flag: "CR"},
    {id: 38, name: "COCOS-KEELING IS", flag: "CC"},
    {id: 39, name: "COMOROS", deleted: true},
    {id: 40, name: "CRETE", flag: "GR"},
    {id: 41, name: "CROZET", flag: "FR"},
    {id: 42, name: "DAMAO, DUI", deleted: true},
    {id: 43, name: "DESECHEO IS", flag: "PR"},
    {id: 44, name: "DESROCHES", deleted: true},
    {id: 45, name: "DODECANESE", flag: "GR"},
    {id: 46, name: "EAST MALAYSIA", flag: "MY"},
    {id: 47, name: "EASTER IS", flag: "CL"},
    {id: 48, name: "EASTERN KIRIBATI", flag: "KI"},
    {id: 49, name: "EQUATORIAL GUINEA", flag: "GQ"},
    {id: 50, name: "MEXICO", flag: "MX"},
    {id: 51, name: "ERITREA", flag: "ER"},
    {id: 52, name: "ESTONIA", flag: "EE"},
    {id: 53, name: "ETHIOPIA", flag: "ET"},
    {id: 54, name: "EUROPEAN RUSSIA", flag: "RU"},
    {id: 55, name: "FARQUHAR", deleted: true, flag: "SC"},
    {id: 56, name: "FERNANDO DE NORONHA", flag: "BR"},
    {id: 57, name: "FRENCH EQ. AFRICA", deleted: true, flag: "FR"},
    {id: 58, name: "FRENCH INDO-CHINA", deleted: true, flag: "FR"},
    {id: 59, name: "FRENCH WEST AFRICA", deleted: true, flag: "FR"},
    {id: 60, name: "BAHAMAS", flag: "BS"},
    {id: 61, name: "FRANZ JOSEF LAND", flag: "RU"},
    {id: 62, name: "BARBADOS", flag: "BB"},
    {id: 63, name: "FRENCH GUIANA", flag: "FR"},
    {id: 64, name: "BERMUDA", flag: "BM"},
    {id: 65, name: "BRITISH VIRGIN IS", flag: "VG"},
    {id: 66, name: "BELIZE", flag: "BZ"},
    {id: 67, name: "FRENCH INDIA", deleted: true, flat: "FR"},
    {id: 68, name: "SAUDI/KUWAIT N.Z.", deleted: true},
    {id: 69, name: "CAYMAN ISLANDS", flag: "KY"},
    {id: 70, name: "CUBA", flag: "CU"},
    {id: 71, name: "GALAPAGOS", flag: "EC"},
    {id: 72, name: "DOMINICAN REPUBLIC", flag: "DO"},
    null,
    {id: 74, name: "EL SALVADOR", flag: "SV"},
    {id: 75, name: "GEORGIA", flag: "GE"},
    {id: 76, name: "GUATEMALA", flag: "GT"},
    {id: 77, name: "GRENADA", flag: "GD"},
    {id: 78, name: "HAITI", flag: "HT"},
    {id: 79, name: "GUADELOUPE", flag: "FR"},
    {id: 80, name: "HONDURAS", flag: "HN"},
    {id: 81, name: "GERMANY", deleted: true},
    {id: 82, name: "JAMAICA", flag: "JM"},
    null,
    {id: 84, name: "MARTINIQUE", flag: "MQ"},
    {id: 85, name: "BONAIRE,CURACAO", deleted: true},
    {id: 86, name: "NICARAGUA", flag: "NI"},
    null,
    {id: 88, name: "PANAMA", flag: "PA"},
    {id: 89, name: "TURKS & CAICOS IS", flag: "TC"},
    {id: 90, name: "TRINIDAD & TOBAGO", flag: "TT"},
    {id: 91, name: "ARUBA", flag: "AW"},
    null,
    {id: 93, name: "GEYSER REEF", deleted: true},
    {id: 94, name: "ANTIGUA & BARBUDA", flag: "AG"},
    {id: 95, name: "DOMINICA", flag: "DM"},
    {id: 96, name: "MONTSERRAT", flag: "MS"},
    {id: 97, name: "ST LUCIA", flag: "LC"},
    {id: 98, name: "ST VINCENT", flag: "VC"},
    {id: 99, name: "GLORIOSO IS", flag: "FR"},
    {id: 100, name: "ARGENTINA", flag: "AR"},
    {id: 101, name: "GOA", deleted: true},
    {id: 102, name: "GOLD COAST, TOGOLAND", deleted: true},
    {id: 103, name: "GUAM", flag: "GU"},
    {id: 104, name: "BOLIVIA", flag: "BO"},
    {id: 105, name: "GUANTANAMO BAY", flag: "US"},
    {id: 106, name: "GUERNSEY", flag: "GG"},
    {id: 107, name: "GUINEA", flag: "GN"},
    {id: 108, name: "BRAZIL", flag: "BR"},
    {id: 109, name: "GUINEA-BISSAU", flag: "GW"},
    {id: 110, name: "HAWAII", flag: "US"},
    {id: 111, name: "HEARD IS", flag: "AU"},
    {id: 112, name: "CHILE", flag: "CL"},
    {id: 113, name: "IFNI", deleted: true},
    {id: 114, name: "ISLE OF MAN", flag: "IM"},
    {id: 115, name: "ITALIAN SOMALI", deleted: true, flag: "IT"},
    {id: 116, name: "COLOMBIA", flag: "CO"},
    {id: 117, name: "ITU HQ", flag: "CH"},
    {id: 118, name: "JAN MAYEN", flag: "NO"},
    {id: 119, name: "JAVA", deleted: true},
    {id: 120, name: "ECUADOR", flag: "EC"},
    null,
    {id: 122, name: "JERSEY", flag: "JE"},
    {id: 123, name: "JOHNSTON IS", flag: "US"},
    {id: 124, name: "JUAN DE NOVA", flag: "FR"},
    {id: 125, name: "JUAN FERNANDEZ", flag: "CL"},
    {id: 126, name: "KALININGRAD", flag: "RU"},
    {id: 127, name: "KAMARAN IS", deleted: true},
    {id: 128, name: "KARELO-FINN REP", deleted: true},
    {id: 129, name: "GUYANA", flag: "GY"},
    {id: 130, name: "KAZAKHSTAN", flag: "KZ"},
    {id: 131, name: "KERGUELEN", flag: "FR"},
    {id: 132, name: "PARAGUAY", flag: "PY"},
    {id: 133, name: "KERMADEC", flag: "NZ"},
    {id: 134, name: "KINGMAN REEF", flag: "US"},
    {id: 135, name: "KYRGYZSTAN", flag: "KG"},
    {id: 136, name: "PERU", flag: "PE"},
    {id: 137, name: "REPUBLIC OF KOREA", flag: "KR"},
    {id: 138, name: "KURE ISLAND", flag: "US"},
    {id: 139, name: "KURIA MURIA IS", deleted: true},
    {id: 140, name: "SURINAME", flag: "SR"},
    {id: 141, name: "FALKLAND IS", flag: "FK"},
    {id: 142, name: "LAKSHADWEEP ISLANDS", flag: "IN"},
    {id: 143, name: "LAOS", flag: "LA"},
    {id: 144, name: "URUGUAY", flag: "UY"},
    {id: 145, name: "LATVIA", flag: "LV"},
    {id: 146, name: "LITHUANIA", flag: "LT"},
    {id: 147, name: "LORD HOWE IS", flag: "AU"},
    {id: 148, name: "VENEZUELA", flag: "VE"},
    {id: 149, name: "AZORES", flag: "PT"},
    {id: 150, name: "AUSTRALIA", flag: "AU"},
    {id: 151, name: "MALYJ VYSOTSKI IS ", deleted: true},
    {id: 152, name: "MACAO", flag: "MO"},
    {id: 153, name: "MACQUARIE IS", flag: "AU"},
    {id: 154, name: "YEMEN ARAB REP", deleted: true},
    {id: 155, name: "MALAYA", deleted: true},
    null,
    {id: 157, name: "NAURU", flag: "NR"},
    {id: 158, name: "VANUATU", flag: "VU"},
    {id: 159, name: "MALDIVES", flag: "MV"},
    {id: 160, name: "TONGA", flag: "TO"},
    {id: 161, name: "MALPELO IS", flag: "CO"},
    {id: 162, name: "NEW CALEDONIA", flag: "NC"},
    {id: 163, name: "PAPUA NEW GUINEA", flag: "PG"},
    {id: 164, name: "MANCHURIA", deleted: true},
    {id: 165, name: "MAURITIUS IS", flag: "MU"},
    {id: 166, name: "MARIANA IS", flag: "US"},
    {id: 167, name: "MARKET REEF", flag: "SE"},
    {id: 168, name: "MARSHALL IS", flag: "MH"},
    {id: 169, name: "MAYOTTE", flag: "YT"},
    {id: 170, name: "NEW ZEALAND", flag: "NZ"},
    {id: 171, name: "MELLISH REEF", flag: "AU"},
    {id: 172, name: "PITCAIRN IS", flag: "PN"},
    {id: 173, name: "MICRONESIA", flag: "FM"},
    {id: 174, name: "MIDWAY IS", flag: "US"},
    {id: 175, name: "FRENCH POLYNESIA", flag: "PF"},
    {id: 176, name: "FIJI", flag: "FJ"},
    {id: 177, name: "MINAMI TORISHIMA", flag: "JP"},
    {id: 178, name: "MINERVA REEF", deleted: true},
    {id: 179, name: "MOLDOVA", flag: "MD"},
    {id: 180, name: "MOUNT ATHOS", flag: "GR"},
    {id: 181, name: "MOZAMBIQUE", flag: "MZ"},
    {id: 182, name: "NAVASSA IS", flag: "US"},
    {id: 183, name: "NETHERLANDS BORNEO", deleted: true},
    {id: 184, name: "NETHERLANDS N GUINEA ", deleted: true},
    {id: 185, name: "SOLOMON ISLANDS", flag: "SB"},
    {id: 186, name: "NEWFOUNDLAND, LABRADOR", deleted: true},
    {id: 187, name: "NIGER", flag: "NE"},
    {id: 188, name: "NIUE", flag: "NU"},
    {id: 189, name: "NORFOLK IS", flag: "NF"},
    {id: 190, name: "SAMOA", flag: "WS"},
    {id: 191, name: "N COOK IS", flag: "NZ"},
    {id: 192, name: "OGASAWARA", flag: "JP"},
    {id: 193, name: "OKINAWA", deleted: true},
    {id: 194, name: "OKINO TORI-SHIMA", deleted: true},
    {id: 195, name: "ANNOBON I.", flag: "GQ"},
    {id: 196, name: "PALESTINE", deleted: true},
    {id: 197, name: "PALMYRA & JARVIS IS", flag: "US"},
    {id: 198, name: "PAPUA TERR", deleted: true},
    {id: 199, name: "PETER I IS", flag: "NO"},
    {id: 200, name: "PORTUGUESE TIMOR", deleted: true},
    {id: 201, name: "PRINCE EDWARD & MARION", flag: "ZA"},
    {id: 202, name: "PUERTO RICO", flag: "PR"},
    {id: 203, name: "ANDORRA", flag: "AD"},
    {id: 204, name: "REVILLAGIGEDO", flag: "MX"},
    {id: 205, name: "ASCENSION ISLAND", flag: "GB"},
    {id: 206, name: "AUSTRIA", flat: "AT"},
    {id: 207, name: "RODRIGUEZ IS", flag: "MU"},
    {id: 208, name: "RUANDA-URUNDI", deleted: true},
    {id: 209, name: "BELGIUM", flag: "BE"},
    {id: 210, name: "SAAR", deleted: true},
    {id: 211, name: "SABLE ISLAND", flag: "CA"},
    {id: 212, name: "BULGARIA", flag: "BG"},
    {id: 213, name: "SAINT MARTIN", flag:"FR"},
    {id: 214, name: "CORSICA", flag: "FR"},
    {id: 215, name: "CYPRUS", flag: "CY"},
    {id: 216, name: "SAN ANDRES & PROVIDENCIA", flag: "NI"},
    {id: 217, name: "SAN FELIX", flag: "CL"},
    {id: 218, name: "CZECHOSLOVAKIA", deleted: true},
    {id: 219, name: "SAO TOME & PRINCIPE", flag: "ST"},
    {id: 220, name: "SARAWAK", deleted: true},
    {id: 221, name: "DENMARK", flag: "DK"},
    {id: 222, name: "FAROE IS", flag: "FO"},
    {id: 223, name: "ENGLAND", flag: "england"},
    {id: 224, name: "FINLAND", flag: "FI"},
    {id: 225, name: "SARDINIA", flag: "IT"},
    {id: 226, name: "SAUDI/IRAQ N.Z.", deleted: true},
    {id: 227, name: "FRANCE", flag: "FR"},
    {id: 228, name: "SERRANA BANK & RONCADOR CAY", deleted: true},
    {id: 229, name: "GERMAN DEM. REP.", deleted: true},
    {id: 230, name: "FED REP OF GERMANY", flag: "DE"},
    {id: 231, name: "SIKKIM", deleted: true},
    {id: 232, name: "SOMALIA", flag: "SO"},
    {id: 233, name: "GIBRALTAR", flag: "GI"},
    {id: 234, name: "S COOK IS", flag: "GS"},
    {id: 235, name: "SOUTH GEORGIA IS", flag: "GS"},
    {id: 236, name: "GREECE", flag: "GR"},
    {id: 237, name: "GREENLAND", flag: "GL"},
    {id: 238, name: "SOUTH ORKNEY IS", flag: "GB"},
    {id: 239, name: "HUNGARY", flag: "HU"},
    {id: 240, name: "SOUTH SANDWICH ISLANDS", flag: "GS"},
    {id: 241, name: "SOUTH SHETLAND ISLANDS", flag: "GB"},
    {id: 242, name: "ICELAND", flag: "IS"},
    {id: 243, name: "DEM REP OF YEMEN", deleted: true},
    {id: 244, name: "SOUTHERN SUDAN", deleted: true},
    {id: 245, name: "IRELAND", flag: "IE"},
    {id: 246, name: "SOV MILITARY ORDER OF MALTA", flag: "MT"},
    {id: 247, name: "SPRATLY IS", flag: "PH"},
    {id: 248, name: "ITALY", flag: "IT"},
    {id: 249, name: "ST KITTS & NEVIS", flag: "KN"},
    {id: 250, name: "ST HELENA IS", flag: "SH"},
    {id: 251, name: "LIECHTENSTEIN", flag: "LI"},
    {id: 252, name: "ST PAUL ISLAND", flag: "CA"},
    {id: 253, name: "ST. PETER & ST. PAUL ROCKS", flag: "BR"},
    {id: 254, name: "LUXEMBOURG", flag: "LU"},
    {id: 255, name: "SINT MAARTEN, SABA, ST EUSTATIUS", flag: "NL"},
    {id: 256, name: "MADEIRA IS", flag: "PT"},
    {id: 257, name: "MALTA", flag: "MT"},
    {id: 258, name: "SUMATRA", deleted: true},
    {id: 259, name: "SVALBARD IS", flag: "NO"},
    {id: 260, name: "MONACO", flag: "MC"},
    {id: 261, name: "SWAN ISLAND", deleted: true},
    {id: 262, name: "TAJIKISTAN", flag: "TJ"},
    {id: 263, name: "NETHERLANDS", flag: "NL"},
    {id: 264, name: "TANGIER", deleted: true},
    {id: 265, name: "NORTHERN IRELAND", flag: "GB"},
    {id: 266, name: "NORWAY", flag: "NO"},
    {id: 267, name: "TERR NEW GUINEA", deleted: true},
    {id: 268, name: "TIBET", deleted: true},
    {id: 269, name: "POLAND", flag: "PL"},
    {id: 270, name: "TOKELAU IS", flag: "TK"},
    {id: 271, name: "TRIESTE", deleted: true},
    {id: 272, name: "PORTUGAL", flag: "PT"},
    {id: 273, name: "TRINDADE & MARTIN VAZ ISLANDS", flag: "BR"},
    {id: 274, name: "TRISTAN DA CUNHA & GOUGH IS", flag: "GB"},
    {id: 275, name: "ROMANIA", flag: "RO"},
    {id: 276, name: "TROMELIN", flag: "FR"},
    {id: 277, name: "ST PIERRE & MIQUELON", flag: "CA"},
    {id: 278, name: "SAN MARINO", flag: "SM"},
    {id: 279, name: "SCOTLAND", flag: "scotland"},
    {id: 280, name: "TURKMENISTAN", flag: "TM"},
    {id: 281, name: "SPAIN", flag: "ES"},
    {id: 282, name: "TUVALU", flag: "TV"},
    {id: 283, name: "UK BASES ON CYPRUS", flag: "CY"},
    {id: 284, name: "SWEDEN", flag: "SE"},
    {id: 285, name: "US VIRGIN ISLANDS", flag: "VI"},
    {id: 286, name: "UGANDA", flag: "UG"},
    {id: 287, name: "SWITZERLAND", flag: "CH"},
    {id: 288, name: "UKRAINE", flag: "UA"},
    {id: 289, name: "UNITED NATIONS HQ", flag: "united-nations"},
    null,
    {id: 291, name: "UNITED STATES", flag: "US"},
    {id: 292, name: "UZBEKISTAN", flag: "UZ"},
    {id: 293, name: "VIETNAM", flag: "VN"},
    {id: 294, name: "WALES", flag: "wales"},
    {id: 295, name: "VATICAN", flag: "VA"},
    {id: 296, name: "SERBIA", flag: "RS"},
    {id: 297, name: "WAKE IS", flag: "US"},
    {id: 298, name: "WALLIS & FUTUNA", flag: "WF"},
    {id: 299, name: "WEST MALAYSIA", flag: "MY"},
    null,
    {id: 301, name: "W KIRIBATI", flag: "KI"},
    {id: 302, name: "WESTERN SAHARA", flag: "EH"},
    {id: 303, name: "WILLIS IS", flag: "AU"},
    {id: 304, name: "BAHRAIN", flag: "BH"},
    {id: 305, name: "BANGLADESH", flag: "BD"},
    {id: 306, name: "BHUTAN", flag: "BT"},
    {id: 307, name: "ZANZIBAR", deleted: true},
    {id: 308, name: "COSTA RICA", flag: "CR"},
    {id: 309, name: "MYANMAR", flag: "MM"},
    null,
    null,
    {id: 312, name: "CAMBODIA", flag: "KH"},
    null,
    null,
    {id: 315, name: "SRI LANKA", flag: "LK"},
    null,
    null,
    {id: 318, name: "CHINA", flag: "CN"},
    null,
    null,
    {id: 321, name: "HONG KONG", flag: "HK"},
    null,
    null,
    {id: 324, name: "INDIA", flag: "IN"},
    null,
    null,
    {id: 327, name: "INDONESIA", flag: "ID"},
    null,
    null,
    {id: 330, name: "IRAN", flag: "IR"},
    null,
    null,
    {id: 333, name: "IRAQ", flag: "IQ"},
    null,
    null,
    {id: 336, name: "ISRAEL", flag: "IL"},
    null,
    null,
    {id: 339, name: "JAPAN", flag: "JP"},
    null,
    null,
    {id: 342, name: "JORDAN", flag: "JO"},
    null,
    {id: 344, name: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA", flag: "KP"},
    {id: 345, name: "BRUNEI", flag: "BN"},
    null,
    null,
    {id: 348, name: "KUWAIT", flag: "KW"},
    null,
    null,
    null,
    null,
    null,
    {id: 354, name: "LEBANON", flag: "LB"},
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {id: 363, name: "MONGOLIA", flag: "MN"},
    null,
    null,
    null,
    null,
    null,
    {id: 369, name: "NEPAL", flag: "NP"},
    {id: 370, name: "OMAN", flag: "OM"},
    null,
    {id: 372, name: "PAKISTAN", flag: "PK"},
    null,
    null,
    {id: 375, name: "PHILIPPINES", flag: "PH"},
    {id: 376, name: "QATAR", flag: "QA"},
    null,
    {id: 378, name: "SAUDI ARABIA", flag: "SA"},
    {id: 379, name: "SEYCHELLES", flag: "SC"},
    null,
    {id: 381, name: "SINGAPORE", flag: "SG"},
    {id: 382, name: "DJIBOUTI", flag: "DJ"},
    null,
    {id: 384, name: "SYRIA", flag: "SY"},
    null,
    {id: 386, name: "TAIWAN", flag: "TW"},
    {id: 387, name: "THAILAND", flag: "TH"},
    null,
    null,
    {id: 390, name: "TURKEY", flag: "TR"},
    {id: 391, name: "UNITED ARAB EMIRATES", flag: "AE"},
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {id: 400, name: "ALGERIA", flag: "DZ"},
    {id: 401, name: "ANGOLA", flag: "AO"},
    {id: 402, name: "BOTSWANA", flag: "BW"},
    null,
    {id: 404, name: "BURUNDI", flag: "BI"},
    null,
    {id: 406, name: "CAMEROON", flag: "CM"},
    null,
    {id: 408, name: "CENTRAL AFRICAN REPUBLIC", flag: "CF"},
    {id: 409, name: "CAPE VERDE", flag: "CV"},
    {id: 410, name: "CHAD", flag: "TD"},
    {id: 411, name: "COMOROS", flag: "KM"},
    {id: 412, name: "REPUBLIC OF THE CONGO", flag: "CG"},
    null,
    {id: 414, name: "DEM. REPUBLIC OF THE CONGO", flag: "CD"},
    null,
    {id: 416, name: "BENIN", flag: "BJ"},
    null,
    null,
    null,
    {id: 420, name: "GABON", flag: "GA"},
    null,
    {id: 422, name: "THE GAMBIA", flag: "GM"},
    null,
    {id: 424, name: "GHANA", flag: "GH"},
    null,
    null,
    null,
    {id: 428, name: "COTE D'IVOIRE", flag: "CI"},
    null,
    {id: 430, name: "KENYA", flag: "KE"},
    null,
    {id: 432, name: "LESOTHO", flag: "LS"},
    null,
    {id: 434, name: "LIBERIA", flag: "LR"},
    null,
    {id: 436, name: "LIBYA", flag: "LY"},
    null,
    {id: 438, name: "MADAGASCAR", flag: "MG"},
    null,
    {id: 440, name: "MALAWI", flag: "MW"},
    null,
    {id: 442, name: "MALI", flag: "ML"},
    null,
    {id: 444, name: "MAURITANIA", flag: "MR"},
    null,
    {id: 446, name: "MOROCCO", flag: "MA"},
    null,
    null,
    null,
    {id: 450, name: "NIGERIA", flag: "NG"},
    null,
    {id: 452, name: "ZIMBABWE", flag: "ZW"},
    {id: 453, name: "REUNION", flag: "FR"},
    {id: 454, name: "RWANDA", flag: "RW"},
    null,
    {id: 456, name: "SENEGAL", flag: "SN"},
    null,
    {id: 458, name: "SIERRA LEONE", flag: "SL"},
    null,
    {id: 460, name: "ROTUMA IS", flag: "FJ"},
    null,
    {id: 462, name: "REPUBLIC OF SOUTH AFRICA", flag: "ZA"},
    null,
    {id: 464, name: "NAMIBIA", flag: "NA"},
    null,
    {id: 466, name: "SUDAN", flag: "SD"},
    null,
    {id: 468, name: "SWAZILAND", flag: "SZ"},
    null,
    {id: 470, name: "TANZANIA", flag: "TZ"},
    null,
    null,
    null,
    {id: 474, name: "TUNISIA", flag: "TN"},
    null,
    null,
    null,
    {id: 478, name: "EGYPT", flag: "EG"},
    null,
    {id: 480, name: "BURKINA-FASO", flag: "BF"},
    null,
    {id: 482, name: "ZAMBIA", flag: "ZM"},
    {id: 483, name: "TOGO", flag: "TG"},
    null,
    null,
    null,
    null,
    {id: 488, name: "WALVIS BAY", deleted: true},
    {id: 489, name: "CONWAY REEF", flag: "FJ"},
    {id: 490, name: "BANABA ISLAND", flag: "KI"},
    null,
    {id: 492, name: "YEMEN", flag: "YE"},
    {id: 493, name: "PENGUIN ISLANDS", deleted: true},
    null,
    null,
    null,
    {id: 497, name: "CROATIA", flag: "HR"},
    null,
    {id: 499, name: "SLOVENIA", flag: "SI"},
    null,
    {id: 501, name: "BOSNIA-HERZEGOVINA", flag: "BA"},
    {id: 502, name: "MACEDONIA", flag: "MK"},
    {id: 503, name: "CZECH REPUBLIC", flag: "CZ"},
    {id: 504, name: "SLOVAK REPUBLIC", flag: "SK"},
    {id: 505, name: "PRATAS IS", flag: "TW"},
    {id: 506, name: "SCARBOROUGH REEF", flag: "PH"},
    {id: 507, name: "TEMOTU PROVINCE", flag: "SB"},
    {id: 508, name: "AUSTRAL IS", flag: "PF"},
    {id: 509, name: "MARQUESAS IS", flag: "FR"},
    {id: 510, name: "PALESTINE", flag: "PS"},
    {id: 511, name: "TIMOR-LESTE", flag: "TL"},
    {id: 512, name: "CHESTERFIELD IS", flag: "GB"},
    {id: 513, name: "DUCIE IS", flag: "PN"},
    {id: 514, name: "MONTENEGRO", flag: "ME"},
    {id: 515, name: "SWAINS ISLAND", flag: "US"},
    {id: 516, name: "ST. BARTHELEMY", flag: "FR"},
    {id: 517, name: "CURACAO", flag: "CW"},
    {id: 518, name: "SINT MAARTEN", flag: "NL"},
    {id: 519, name: "ST EUSTATIUS AND SABA", flag: "AN"},
    {id: 520, name: "BONAIRE", flag: "NL"},
    {id: 521, name: "SOUTH SUDAN", flag: "SS"}
];

exports.contests = [
    {id: "070-PSKFEST", desc: "PODXS PSKFest"},
    {id: "070-VALENTINE-SPRINT", desc: "PODXS Valentine Sprint"},
    {id: "070-ST-PATS-DAY", desc: "PODXS St. Patricks Day"},
    {id: "070-31-FLAVORS", desc: "PODXS 31 Flavors"},
    {id: "070-3-DAY", desc: "PODXS Three Day Weekend"},
    {id: "070-40M-SPRINT", desc: "PODXS 40m Firecracker Sprint"},
    {id: "070-80M-SPRINT", desc: "PODXS 80m Jay Hudak Memorial Sprint"},
    {id: "070-160M-SPRINT", desc: "PODXS Great Pumpkin Sprint"},
    {id: "7QP", desc: "7th-Area QSO Party"},
    {id: "AL-QSO-PARTY", desc: "Alabama QSO Party"},
    {id: "ALL-ASIAN-DX-CW", desc: "JARL All Asian DX Contest (CW)"},
    {id: "ALL-ASIAN-DX-PHONE", desc: "JARL All Asian DX Contest (PHONE)"},
    {id: "ANARTS-RTTY", desc: "ANARTS WW RTTY"},
    {id: "ANATOLIAN-RTTY", desc: "Anatolian WW RTTY"},
    {id: "AP-SPRINT", desc: "Asia - Pacific Sprint"},
    {id: "AR-QSO-PARTY", desc: "Arkansas QSO Party"},
    {id: "ARI-DX", desc: "ARI DX Contest"},
    {id: "ARRL-10", desc: "ARRL 10 Meter Contest"},
    {id: "ARRL-160", desc: "ARRL 160 Meter Contest"},
    {id: "ARRL-DX-CW", desc: "ARRL International DX Contest (CW)"},
    {id: "ARRL-DX-SSB", desc: "ARRL International DX Contest (Phone)"},
    {id: "ARRL-FIELD-DAY", desc: "ARRL Field Day"},
    {id: "ARRL-RTTY", desc: "ARRL RTTY Round-Up"},
    {id: "ARRL-SS-CW", desc: "ARRL November Sweepstakes (CW)"},
    {id: "ARRL-SS-SSB", desc: "ARRL November Sweepstakes (Phone)"},
    {id: "ARRL-UHF-AUG", desc: "ARRL August UHF Contest"},
    {id: "ARRL-VHF-JAN", desc: "ARRL January VHF Sweepstakes"},
    {id: "ARRL-VHF-JUN", desc: "ARRL June VHF QSO Party"},
    {id: "ARRL-VHF-SEP", desc: "ARRL September VHF QSO Party"},
    {id: "AZ-QSO-PARTY", desc: "Arizona QSO Party"},
    {id: "BARTG-RTTY", desc: "BARTG Spring RTTY Contest"},
    {id: "BARTG-SPRINT", desc: "BARTG Sprint Contest"},
    {id: "BC-QSO-PARTY", desc: "British Columbia QSO Party"},
    {id: "CA-QSO-PARTY", desc: "California QSO Party"},
    {id: "CO-QSO-PARTY", desc: "Colorado QSO Party"},
    {id: "CQ-160-CW", desc: "CQ WW 160 Meter DX Contest (CW)"},
    {id: "CQ-160-SSB", desc: "CQ WW 160 Meter DX Contest (SSB)"},
    {id: "CQ-M", desc: "CQ-M International DX Contest"},
    {id: "CQ-VHF", desc: "CQ World-Wide VHF Contest"},
    {id: "CQ-WPX-CW", desc: "CQ WW WPX Contest (CW)"},
    {id: "CQ-WPX-RTTY", desc: "CQ/RJ WW RTTY WPX Contest"},
    {id: "CQ-WPX-SSB", desc: "CQ WW WPX Contest (SSB)"},
    {id: "CQ-WW-CW", desc: "CQ WW DX Contest (CW)"},
    {id: "CQ-WW-RTTY", desc: "CQ/RJ WW RTTY DX Contest"},
    {id: "CQ-WW-SSB", desc: "CQ WW DX Contest (SSB)"},
    {id: "CWOPS-CWT", desc: "CWops Mini-CWT Test"},
    {id: "CIS-DX", desc: "CIS DX Contest"},
    {id: "CT-QSO-PARTY", desc: "Connecticut QSO Party"},
    {id: "DARC-WAEDC-CW", desc: "WAE DX Contest (CW)"},
    {id: "DARC-WAEDC-RTTY", desc: "WAE DX Contest (RTTY)"},
    {id: "DARC-WAEDC-SSB", desc: "WAE DX Contest (SSB)"},
    {id: "DARC-WAG", desc: "DARC Worked All Germany"},
    {id: "DE-QSO-PARTY", desc: "Delaware QSO Party"},
    {id: "DL-DX-RTTY", desc: "DL-DX RTTY Contest"},
    {id: "EA-RTTY (Deprecated) ", desc: "Unión de Radioaficionados Españoles RTTY Contest"},
    {id: "EA-WW-RTTY", desc: "Unión de Radioaficionados Españoles RTTY Contest"},
    {id: "EPC-PSK63", desc: "PSK63 QSO Party"},
    {id: "EU Sprint", desc: "EU Sprint"},
    {id: "EUCW160M", desc: "European CW Association 160m CW Party"},
    {id: "EU-HF", desc: "EU HF Championship"},
    {id: "EU-PSK-DX", desc: "EU PSK DX Contest"},
    {id: "Fall Sprint", desc: "FISTS Fall Sprint"},
    {id: "FL-QSO-PARTY", desc: "Florida QSO Party"},
    {id: "GA-QSO-PARTY", desc: "Georgia QSO Party"},
    {id: "HELVETIA", desc: "Helvetia Contest"},
    {id: "HI-QSO-PARTY", desc: "Hawaiian QSO Party"},
    {id: "HOLYLAND", desc: "IARC Holyland Contest"},
    {id: "IARU-FIELD-DAY", desc: "DARC IARU Region 1 Field Day"},
    {id: "IARU-HF", desc: "IARU HF World Championship"},
    {id: "IA-QSO-PARTY", desc: "Iowa QSO Party"},
    {id: "ID-QSO-PARTY", desc: "Idaho QSO Party"},
    {id: "IL QSO Party", desc: "Illinois QSO Party"},
    {id: "IN-QSO-PARTY", desc: "Indiana QSO Party"},
    {id: "JARTS-WW-RTTY", desc: "JARTS WW RTTY"},
    {id: "JIDX-CW", desc: "Japan International DX Contest (CW)"},
    {id: "JIDX-SSB", desc: "Japan International DX Contest (SSB)"},
    {id: "KS-QSO-PARTY", desc: "Kansas QSO Party"},
    {id: "KY-QSO-PARTY", desc: "Kentucky QSO Party"},
    {id: "LA-QSO-PARTY", desc: "Louisiana QSO Party"},
    {id: "LZ DX", desc: "LZ DX Contest"},
    {id: "MAR-QSO-PARTY", desc: "Maritimes QSO Party"},
    {id: "MI-QSO-PARTY", desc: "Michigan QSO Party"},
    {id: "MIDATLANTIC-QSO-PARTY", desc: "Mid-Atlantic QSO Party"},
    {id: "MD-QSO-PARTY", desc: "Maryland QSO Party"},
    {id: "ME-QSO-PARTY", desc: "Maine QSO Party"},
    {id: "MI-QSO-PARTY", desc: "Michigan QSO Party"},
    {id: "MN-QSO-PARTY", desc: "Minnesota QSO Party"},
    {id: "MO-QSO-PARTY", desc: "Missouri QSO Party"},
    {id: "MS-QSO-PARTY", desc: "Mississippi QSO Party"},
    {id: "MT-QSO-PARTY", desc: "Montana QSO Party"},
    {id: "NAQP-CW", desc: "North America QSO Party (CW)"},
    {id: "NAQP-RTTY", desc: "North America QSO Party (RTTY)"},
    {id: "NAQP-SSB", desc: "North America QSO Party (Phone)"},
    {id: "NA-SPRINT-CW", desc: "North America Sprint (CW)"},
    {id: "NA-SPRINT-RTTY", desc: "North America Sprint (RTTY)"},
    {id: "NA-SPRINT-SSB", desc: "North America Sprint (Phone)"},
    {id: "NEQP", desc: "New England QSO Party"},
    {id: "NC-QSO-PARTY", desc: "North Carolina QSO Party"},
    {id: "ND-QSO-PARTY", desc: "North Dakota QSO Party"},
    {id: "NE-QSO-PARTY", desc: "Nebraska QSO Party"},
    {id: "NH-QSO-PARTY", desc: "New Hampshire QSO Party"},
    {id: "NJ-QSO-PARTY", desc: "New Jersey QSO Party"},
    {id: "NM-QSO-PARTY", desc: "New Mexico QSO Party"},
    {id: "NRAU-BALTIC-CW", desc: "NRAU-Baltic Contest (CW)"},
    {id: "NRAU-BALTIC-SSB", desc: "NRAU-Baltic Contest (SSB)"},
    {id: "NV-QSO-PARTY", desc: "Nevada QSO Party"},
    {id: "NY-QSO-PARTY", desc: "New York QSO Party"},
    {id: "OCEANIA-DX-CW", desc: "Oceania DX Contest (CW)"},
    {id: "OCEANIA-DX-SSB", desc: "Oceania DX Contest (SSB)"},
    {id: "OH-QSO-PARTY", desc: "Ohio QSO Party"},
    {id: "OK-DX-RTTY", desc: "Czech Radio Club OK DX Contest"},
    {id: "OK-OM-DX", desc: "Czech Radio Club OK-OM DX Contest"},
    {id: "OK-QSO-PARTY", desc: "Oklahoma QSO Party"},
    {id: "OMISS-QSO-PARTY", desc: "Old Man International Sideband Society QSO Party"},
    {id: "ON-QSO-PARTY", desc: "Ontario QSO Party"},
    {id: "OR-QSO-PARTY", desc: "Oregon QSO Party"},
    {id: "PACC", desc: "Dutch PACC Contest"},
    {id: "PA-QSO-PARTY", desc: "Pennsylvania QSO Party"},
    {id: "QC-QSO-PARTY", desc: "Quebec QSO Party"},
    {id: "RAC ", desc: "Canadian Amateur Radio Society Contest"},
    {id: "RAC-CANADA-DAY", desc: "Canadian Amateur Radio Society Canada Day Contest"},
    {id: "RAC-CANADA-WINTER", desc: "Canadian Amateur Radio Society Canada Winter Contest"},
    {id: "RDAC", desc: "Russian District Award Contest"},
    {id: "RDXC", desc: "Russian DX Contest"},
    {id: "REF-160M", desc: "Reseau des Emetteurs Francais 160m Contest"},
    {id: "REF-CW", desc: "Reseau des Emetteurs Francais Contest (CW)"},
    {id: "REF-SSB", desc: "Reseau des Emetteurs Francais Contest (SSB)"},
    {id: "RI-QSO-PARTY", desc: "Rhode Island QSO Party"},
    {id: "RSGB-160", desc: "1.8Mhz Contest"},
    {id: "RSGB-21/28-CW", desc: "21/28 MHz Contest (CW)"},
    {id: "RSGB-21/28-SSB", desc: "21/28 MHz Contest (SSB)"},
    {id: "RSGB-80M-CC", desc: "80m Club Championships"},
    {id: "RSGB-AFS-CW", desc: "Affiliated Societies Team Contest (CW)"},
    {id: "RSGB-AFS-SSB", desc: "Affiliated Societies Team Contest (SSB)"},
    {id: "RSGB-CLUB-CALLS", desc: "Club Calls"},
    {id: "RSGB-COMMONWEALTH", desc: "Commonwealth Contest"},
    {id: "RSGB-IOTA", desc: "IOTA Contest"},
    {id: "RSGB-LOW-POWER", desc: "Low Power Field Day"},
    {id: "RSGB-NFD", desc: "National Field Day"},
    {id: "RSGB-ROPOCO", desc: "RoPoCo"},
    {id: "RSGB-SSB-FD", desc: "SSB Field Day"},
    {id: "RUSSIAN-RTTY", desc: "Russian Radio RTTY Worldwide Contest"},
    {id: "SAC-CW", desc: "Scandinavian Activity Contest (CW)"},
    {id: "SAC-SSB", desc: "Scandinavian Activity Contest (SSB)"},
    {id: "SARTG-RTTY", desc: "SARTG WW RTTY"},
    {id: "SCC-RTTY", desc: "SCC RTTY Championship"},
    {id: "SC-QSO-PARTY", desc: "South Carolina QSO Party"},
    {id: "SD-QSO-PARTY", desc: "South Dakota QSO Party"},
    {id: "SMP-AUG", desc: "SSA Portabeltest"},
    {id: "SMP-MAY", desc: "SSA Portabeltest"},
    {id: "SPDXContest", desc: "SP DX Contest"},
    {id: "SP-DX-RTTY", desc: "PRC SPDX Contest (RTTY)"},
    {id: "Spring Sprint", desc: "FISTS Spring Sprint"},
    {id: "SR-MARATHON", desc: "Scottish-Russian Marathon"},
    {id: "STEW-PERRY", desc: "Stew Perry Topband Distance Challenge"},
    {id: "Summer Sprint", desc: "FISTS Summer Sprint"},
    {id: "TARA-RTTY", desc: "TARA RTTY Mêlée"},
    {id: "TMC-RTTY", desc: "The Makrothen Contest"},
    {id: "TN-QSO-PARTY", desc: "Tennessee QSO Party"},
    {id: "TX-QSO-PARTY", desc: "Texas QSO Party"},
    {id: "UBA-DX-CW", desc: "UBA Contest (CW)"},
    {id: "UBA-DX-SSB", desc: "UBA Contest (SSB)"},
    {id: "UK-DX-BPSK63", desc: "European PSK Club BPSK63 Contest"},
    {id: "UK-DX-RTTY", desc: "UK DX RTTY Contest"},
    {id: "UKRAINIAN DX", desc: "Ukrainian DX"},
    {id: "UKR-CHAMP-RTTY", desc: "Open Ukraine RTTY Championship"},
    {id: "URE-DX", desc: "Ukrainian DX Contest"},
    {id: "US-COUNTIES-QSO", desc: "Mobile Amateur Awards Club"},
    {id: "UT-QSO-PARTY", desc: "Utah QSO Party"},
    {id: "VENEZ-IND-DAY", desc: "RCV Venezuelan Independence Day Contest"},
    {id: "Virginia QSO Party (deprecated) ", desc: "Virginia QSO Party"},
    {id: "VA-QSO-PARTY", desc: "Virginia QSO Party"},
    {id: "VOLTA-RTTY", desc: "Alessandro Volta RTTY DX Contest"},
    {id: "WA-QSO-PARTY", desc: "Washington QSO Party"},
    {id: "WI-QSO-PARTY", desc: "Wisconsin QSO Party"},
    {id: "WV-QSO-PARTY", desc: "West Virginia QSO Party"},
    {id: "WY-QSO-PARTY", desc: "Wyoming QSO Party"},
    {id: "Winter Sprint", desc: "FISTS Winter Sprint"},
    {id: "XE-INTL-RTTY", desc: "Mexico International Contest (RTTY)"},
    {id: "YUDXC", desc: "YU DX Contest"}
]
